services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: express-ecommerce_container
      restart: always
      ports:
        - '8000:8000'
      env_file:
        - .env
      depends_on:
        - db
      network: 
        - express_network

  db:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_PASSWORD=empatbelas
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - '7654:5432'
    network: 
      - express_network

networks:
  express_network: